from __future__ import annotations

from dataclasses import dataclass, replace

from .models import Platform


@dataclass(frozen=True)
class PlatformSpec:
    id: Platform
    name: str
    short_name: str
    brand: str
    generation: str
    kind: str
    icon: str
    color: str
    extensions: tuple[str, ...]
    rom_extensions: tuple[str, ...]
    dat_aliases: tuple[str, ...]
    dat_recommended: str
    dat_family: str = "nointro"
    romset_recommended: str = "No-Intro ROM set que coincida con la variante del DAT seleccionado."
    collection_tip: str = "Para 1G1R, usa Parent/Clone XML y prioriza regiones/idiomas en Perfil."
    hash_mode: str = "direct"
    ra_console_id: int | None = None
    ra_active: bool = True
    complexity: str = "simple"
    notes: str = ""

    @property
    def extension_label(self) -> str:
        return ", ".join(self.rom_extensions)

    @property
    def supports_ra(self) -> bool:
        return self.ra_console_id is not None

    @property
    def ra_label(self) -> str:
        if self.ra_console_id is None:
            return "sin RA"
        return "RA" if self.ra_active else "RA inactivo"

    @property
    def icon_url(self) -> str | None:
        if self.ra_console_id is None:
            return None
        return RA_ICON_URLS.get(self.ra_console_id)


RA_ICON_URLS: dict[int, str] = {
    1: "https://static.retroachievements.org/assets/images/system/md.png",
    2: "https://static.retroachievements.org/assets/images/system/n64.png",
    3: "https://static.retroachievements.org/assets/images/system/snes.png",
    4: "https://static.retroachievements.org/assets/images/system/gb.png",
    5: "https://static.retroachievements.org/assets/images/system/gba.png",
    6: "https://static.retroachievements.org/assets/images/system/gbc.png",
    7: "https://static.retroachievements.org/assets/images/system/nes.png",
    8: "https://static.retroachievements.org/assets/images/system/pce.png",
    9: "https://static.retroachievements.org/assets/images/system/scd.png",
    10: "https://static.retroachievements.org/assets/images/system/32x.png",
    11: "https://static.retroachievements.org/assets/images/system/sms.png",
    12: "https://static.retroachievements.org/assets/images/system/psx.png",
    13: "https://static.retroachievements.org/assets/images/system/lynx.png",
    14: "https://static.retroachievements.org/assets/images/system/ngp.png",
    15: "https://static.retroachievements.org/assets/images/system/gg.png",
    16: "https://static.retroachievements.org/assets/images/system/gc.png",
    17: "https://static.retroachievements.org/assets/images/system/jag.png",
    18: "https://static.retroachievements.org/assets/images/system/nds.png",
    19: "https://static.retroachievements.org/assets/images/system/wii.png",
    20: "https://static.retroachievements.org/assets/images/system/wiiu.png",
    21: "https://static.retroachievements.org/assets/images/system/ps2.png",
    22: "https://static.retroachievements.org/assets/images/system/xbox.png",
    23: "https://static.retroachievements.org/assets/images/system/odyssey2.png",
    24: "https://static.retroachievements.org/assets/images/system/pkmnmini.png",
    25: "https://static.retroachievements.org/assets/images/system/a2600.png",
    27: "https://static.retroachievements.org/assets/images/system/arc.png",
    28: "https://static.retroachievements.org/assets/images/system/vboy.png",
    29: "https://static.retroachievements.org/assets/images/system/msx.png",
    30: "https://static.retroachievements.org/assets/images/system/c64.png",
    34: "https://static.retroachievements.org/assets/images/system/vic20.png",
    35: "https://static.retroachievements.org/assets/images/system/amiga.png",
    36: "https://static.retroachievements.org/assets/images/system/ast.png",
    37: "https://static.retroachievements.org/assets/images/system/cpc.png",
    38: "https://static.retroachievements.org/assets/images/system/a2.png",
    39: "https://static.retroachievements.org/assets/images/system/sat.png",
    40: "https://static.retroachievements.org/assets/images/system/dc.png",
    41: "https://static.retroachievements.org/assets/images/system/psp.png",
    42: "https://static.retroachievements.org/assets/images/system/cdi.png",
    43: "https://static.retroachievements.org/assets/images/system/3do.png",
    44: "https://static.retroachievements.org/assets/images/system/coleco.png",
    45: "https://static.retroachievements.org/assets/images/system/intv.png",
    46: "https://static.retroachievements.org/assets/images/system/vectrex.png",
    47: "https://static.retroachievements.org/assets/images/system/8088.png",
    48: "https://static.retroachievements.org/assets/images/system/9800.png",
    49: "https://static.retroachievements.org/assets/images/system/pc-fx.png",
    50: "https://static.retroachievements.org/assets/images/system/5200.png",
    51: "https://static.retroachievements.org/assets/images/system/7800.png",
    52: "https://static.retroachievements.org/assets/images/system/x68k.png",
    53: "https://static.retroachievements.org/assets/images/system/ws.png",
    55: "https://static.retroachievements.org/assets/images/system/scv.png",
    56: "https://static.retroachievements.org/assets/images/system/ngcd.png",
    57: "https://static.retroachievements.org/assets/images/system/chf.png",
    59: "https://static.retroachievements.org/assets/images/system/zxs.png",
    60: "https://static.retroachievements.org/assets/images/system/gw.png",
    61: "https://static.retroachievements.org/assets/images/system/ngage.png",
    62: "https://static.retroachievements.org/assets/images/system/3ds.png",
    63: "https://static.retroachievements.org/assets/images/system/sv.png",
    64: "https://static.retroachievements.org/assets/images/system/x1.png",
    68: "https://static.retroachievements.org/assets/images/system/pico.png",
    69: "https://static.retroachievements.org/assets/images/system/megaduck.png",
    70: "https://static.retroachievements.org/assets/images/system/zeebo.png",
    71: "https://static.retroachievements.org/assets/images/system/arduboy.png",
    72: "https://static.retroachievements.org/assets/images/system/wasm4.png",
    73: "https://static.retroachievements.org/assets/images/system/arcadia.png",
    74: "https://static.retroachievements.org/assets/images/system/vc4000.png",
    75: "https://static.retroachievements.org/assets/images/system/elektor.png",
    76: "https://static.retroachievements.org/assets/images/system/pcecd.png",
    77: "https://static.retroachievements.org/assets/images/system/jagcd.png",
    78: "https://static.retroachievements.org/assets/images/system/dsi.png",
    80: "https://static.retroachievements.org/assets/images/system/uzebox.png",
    81: "https://static.retroachievements.org/assets/images/system/fds.png",
    82: "https://static.retroachievements.org/assets/images/system/ps3.png",
}


PLATFORM_SPECS: dict[Platform, PlatformSpec] = {
    Platform.NES: PlatformSpec(
        id=Platform.NES,
        name="Nintendo Entertainment System / Famicom",
        short_name="NES / Famicom",
        brand="Nintendo",
        generation="3a gen",
        kind="sobremesa",
        icon="sports_esports",
        color="red",
        extensions=(".nes", ".unh", ".unif", ".zip"),
        rom_extensions=(".nes", ".unh", ".unif"),
        dat_aliases=("Nintendo - Nintendo Entertainment System", "Nintendo - Famicom"),
        dat_recommended="No-Intro Headered Parent/Clone XML",
        romset_recommended="NES headered/iNES si quieres máxima compatibilidad de emulación; unheadered solo con DAT unheadered.",
        collection_tip="Para RA, RetroPerfect calcula el hash ignorando el header iNES; para 1G1R conserva Headered recomendado.",
        hash_mode="nes",
        ra_console_id=7,
        complexity="especial",
        notes="Headered recomendado para emulacion; RA ignora el header iNES.",
    ),
    Platform.FDS: PlatformSpec(
        id=Platform.FDS,
        name="Famicom Disk System",
        short_name="FDS",
        brand="Nintendo",
        generation="3a gen",
        kind="sobremesa",
        icon="album",
        color="red",
        extensions=(".fds", ".qd", ".zip"),
        rom_extensions=(".fds", ".qd"),
        dat_aliases=("Nintendo - Famicom Disk System",),
        dat_recommended="No-Intro Parent/Clone XML",
        romset_recommended="FDS del mismo modo que el DAT; evita mezclar dumps con cabecera diferente.",
        hash_mode="fds",
        ra_console_id=28,
        complexity="especial",
        notes="Puede tener variantes de cabecera/formato; validar DAT elegido antes de aplicar.",
    ),
    Platform.SNES: PlatformSpec(
        id=Platform.SNES,
        name="Super Nintendo / Super Famicom",
        short_name="SNES / SFC",
        brand="Nintendo",
        generation="4a gen",
        kind="sobremesa",
        icon="developer_board",
        color="purple",
        extensions=(".sfc", ".smc", ".fig", ".swc", ".zip"),
        rom_extensions=(".sfc", ".smc", ".fig", ".swc"),
        dat_aliases=("Nintendo - Super Nintendo Entertainment System",),
        dat_recommended="No-Intro Parent/Clone XML",
        romset_recommended="Preferible SFC/headerless; si aparece SMC con copier header se intenta normalizar.",
        hash_mode="snes",
        ra_console_id=3,
        complexity="especial",
        notes="Se intenta normalizar el copier header de 512 bytes.",
    ),
    Platform.GB: PlatformSpec(
        id=Platform.GB,
        name="Game Boy",
        short_name="Game Boy",
        brand="Nintendo",
        generation="portatil clasica",
        kind="portatil",
        icon="stay_current_portrait",
        color="gray",
        extensions=(".gb", ".sgb", ".zip"),
        rom_extensions=(".gb", ".sgb"),
        dat_aliases=("Nintendo - Game Boy",),
        dat_recommended="No-Intro Parent/Clone XML",
        hash_mode="direct",
        ra_console_id=4,
    ),
    Platform.GBC: PlatformSpec(
        id=Platform.GBC,
        name="Game Boy Color",
        short_name="Game Boy Color",
        brand="Nintendo",
        generation="portatil clasica",
        kind="portatil",
        icon="phone_iphone",
        color="indigo",
        extensions=(".gbc", ".zip"),
        rom_extensions=(".gbc",),
        dat_aliases=("Nintendo - Game Boy Color",),
        dat_recommended="No-Intro Parent/Clone XML",
        hash_mode="direct",
        ra_console_id=6,
    ),
    Platform.GBA: PlatformSpec(
        id=Platform.GBA,
        name="Game Boy Advance",
        short_name="Game Boy Advance",
        brand="Nintendo",
        generation="6a gen",
        kind="portatil",
        icon="smartphone",
        color="deep-purple",
        extensions=(".gba", ".agb", ".zip"),
        rom_extensions=(".gba", ".agb"),
        dat_aliases=("Nintendo - Game Boy Advance",),
        dat_recommended="No-Intro Parent/Clone XML",
        hash_mode="direct",
        ra_console_id=5,
    ),
    Platform.VB: PlatformSpec(
        id=Platform.VB,
        name="Virtual Boy",
        short_name="Virtual Boy",
        brand="Nintendo",
        generation="5a gen",
        kind="sobremesa",
        icon="view_in_ar",
        color="red",
        extensions=(".vb", ".vboy", ".bin", ".zip"),
        rom_extensions=(".vb", ".vboy", ".bin"),
        dat_aliases=("Nintendo - Virtual Boy",),
        dat_recommended="No-Intro Parent/Clone XML",
        hash_mode="direct",
        ra_console_id=21,
    ),
    Platform.N64: PlatformSpec(
        id=Platform.N64,
        name="Nintendo 64",
        short_name="Nintendo 64",
        brand="Nintendo",
        generation="5a gen",
        kind="sobremesa",
        icon="view_module",
        color="green",
        extensions=(".z64", ".n64", ".v64", ".rom", ".zip"),
        rom_extensions=(".z64", ".n64", ".v64", ".rom"),
        dat_aliases=("Nintendo - Nintendo 64",),
        dat_recommended="No-Intro BigEndian Parent/Clone XML",
        romset_recommended="Preferible .z64 BigEndian. Si el romset tiene .n64/.v64 se intenta normalizar al hash BigEndian.",
        collection_tip="No mezcles DAT BigEndian y ByteSwapped si quieres un resumen fácil de leer.",
        hash_mode="n64",
        ra_console_id=2,
        complexity="especial",
        notes="Se intenta normalizar byte-swapped/little-endian a BigEndian para DAT.",
    ),
    Platform.NDS: PlatformSpec(
        id=Platform.NDS,
        name="Nintendo DS",
        short_name="Nintendo DS",
        brand="Nintendo",
        generation="7a gen",
        kind="portatil",
        icon="filter_none",
        color="blue",
        extensions=(".nds", ".srl", ".zip"),
        rom_extensions=(".nds", ".srl"),
        dat_aliases=("Nintendo - Nintendo DS",),
        dat_recommended="No-Intro Decrypted/standard Parent/Clone XML",
        romset_recommended="Nintendo DS decrypted/standard .nds; DSi/CDN/encrypted queda fuera del flujo estable.",
        hash_mode="nds",
        ra_console_id=18,
        complexity="especial",
        notes="DSi/CDN/encrypted queda fuera del flujo estable inicial.",
    ),
    Platform.SMS: PlatformSpec(
        id=Platform.SMS,
        name="Master System / Mark III",
        short_name="Master System",
        brand="Sega",
        generation="3a gen",
        kind="sobremesa",
        icon="gamepad",
        color="blue",
        extensions=(".sms", ".sg", ".bin", ".zip"),
        rom_extensions=(".sms", ".sg", ".bin"),
        dat_aliases=("Sega - Master System - Mark III",),
        dat_recommended="No-Intro Parent/Clone XML",
        ra_console_id=11,
    ),
    Platform.GG: PlatformSpec(
        id=Platform.GG,
        name="Game Gear",
        short_name="Game Gear",
        brand="Sega",
        generation="portatil clasica",
        kind="portatil",
        icon="stay_current_landscape",
        color="cyan",
        extensions=(".gg", ".bin", ".zip"),
        rom_extensions=(".gg", ".bin"),
        dat_aliases=("Sega - Game Gear",),
        dat_recommended="No-Intro Parent/Clone XML",
        ra_console_id=15,
    ),
    Platform.MD: PlatformSpec(
        id=Platform.MD,
        name="Mega Drive / Genesis",
        short_name="Mega Drive",
        brand="Sega",
        generation="4a gen",
        kind="sobremesa",
        icon="memory",
        color="blue-grey",
        extensions=(".md", ".gen", ".bin", ".smd", ".zip"),
        rom_extensions=(".md", ".gen", ".bin", ".smd"),
        dat_aliases=("Sega - Mega Drive - Genesis",),
        dat_recommended="No-Intro Parent/Clone XML",
        hash_mode="direct",
        ra_console_id=1,
        complexity="especial",
        notes="SMD interleaved puede requerir normalizacion posterior.",
    ),
    Platform.S32X: PlatformSpec(
        id=Platform.S32X,
        name="Sega 32X",
        short_name="32X",
        brand="Sega",
        generation="5a gen",
        kind="sobremesa",
        icon="extension",
        color="blue-grey",
        extensions=(".32x", ".bin", ".zip"),
        rom_extensions=(".32x", ".bin"),
        dat_aliases=("Sega - 32X",),
        dat_recommended="No-Intro Parent/Clone XML",
        ra_console_id=10,
    ),
    Platform.SG1000: PlatformSpec(
        id=Platform.SG1000,
        name="SG-1000",
        short_name="SG-1000",
        brand="Sega",
        generation="2a gen",
        kind="sobremesa",
        icon="videogame_asset",
        color="blue",
        extensions=(".sg", ".sc", ".bin", ".zip"),
        rom_extensions=(".sg", ".sc", ".bin"),
        dat_aliases=("Sega - SG-1000",),
        dat_recommended="No-Intro Parent/Clone XML",
        ra_console_id=33,
    ),
    Platform.PCE: PlatformSpec(
        id=Platform.PCE,
        name="PC Engine / TurboGrafx-16",
        short_name="PC Engine",
        brand="NEC",
        generation="4a gen",
        kind="sobremesa",
        icon="radio_button_checked",
        color="orange",
        extensions=(".pce", ".bin", ".zip"),
        rom_extensions=(".pce", ".bin"),
        dat_aliases=("NEC - PC Engine - TurboGrafx 16",),
        hash_mode="pce",
        dat_recommended="No-Intro Parent/Clone XML",
        ra_console_id=8,
    ),
    Platform.SGX: PlatformSpec(
        id=Platform.SGX,
        name="PC Engine SuperGrafx",
        short_name="SuperGrafx",
        brand="NEC",
        generation="4a gen",
        kind="sobremesa",
        icon="adjust",
        color="orange",
        extensions=(".sgx", ".pce", ".bin", ".zip"),
        rom_extensions=(".sgx", ".pce", ".bin"),
        dat_aliases=("NEC - PC Engine SuperGrafx",),
        hash_mode="pce",
        dat_recommended="No-Intro Parent/Clone XML",
        ra_console_id=105,
    ),
    Platform.A2600: PlatformSpec(
        id=Platform.A2600,
        name="Atari 2600",
        short_name="Atari 2600",
        brand="Atari",
        generation="2a gen",
        kind="sobremesa",
        icon="casino",
        color="brown",
        extensions=(".a26", ".bin", ".zip"),
        rom_extensions=(".a26", ".bin"),
        dat_aliases=("Atari - 2600",),
        dat_recommended="No-Intro Parent/Clone XML",
        ra_console_id=25,
    ),
    Platform.A5200: PlatformSpec(
        id=Platform.A5200,
        name="Atari 5200",
        short_name="Atari 5200",
        brand="Atari",
        generation="2a gen",
        kind="sobremesa",
        icon="videogame_asset",
        color="brown",
        extensions=(".a52", ".bin", ".zip"),
        rom_extensions=(".a52", ".bin"),
        dat_aliases=("Atari - 5200",),
        dat_recommended="No-Intro Parent/Clone XML",
        ra_console_id=26,
    ),
    Platform.A7800: PlatformSpec(
        id=Platform.A7800,
        name="Atari 7800",
        short_name="Atari 7800",
        brand="Atari",
        generation="3a gen",
        kind="sobremesa",
        icon="dashboard",
        color="brown",
        extensions=(".a78", ".bin", ".zip"),
        rom_extensions=(".a78", ".bin"),
        dat_aliases=("Atari - 7800",),
        hash_mode="a78",
        dat_recommended="No-Intro A78 Parent/Clone XML",
        romset_recommended="Usa romset A78 si el DAT es A78; BIN solo con DAT BIN.",
        ra_console_id=27,
        complexity="especial",
        notes="Preferir DAT A78 si el romset usa cabecera A78.",
    ),
    Platform.LYNX: PlatformSpec(
        id=Platform.LYNX,
        name="Atari Lynx",
        short_name="Atari Lynx",
        brand="Atari",
        generation="portatil clasica",
        kind="portatil",
        icon="crop_landscape",
        color="brown",
        extensions=(".lnx", ".lyx", ".o", ".zip"),
        rom_extensions=(".lnx", ".lyx", ".o"),
        dat_aliases=("Atari - Lynx",),
        hash_mode="lynx",
        dat_recommended="No-Intro LNX Parent/Clone XML",
        romset_recommended="Preferible LNX si el DAT es LNX; BLL/LYX requieren variante compatible.",
        ra_console_id=13,
        complexity="especial",
    ),
    Platform.JAGUAR: PlatformSpec(
        id=Platform.JAGUAR,
        name="Atari Jaguar",
        short_name="Jaguar",
        brand="Atari",
        generation="5a gen",
        kind="sobremesa",
        icon="view_comfy",
        color="brown",
        extensions=(".j64", ".rom", ".abs", ".cof", ".bin", ".zip"),
        rom_extensions=(".j64", ".rom", ".abs", ".cof", ".bin"),
        dat_aliases=("Atari - Jaguar",),
        dat_recommended="No-Intro J64/ROM segun romset",
        romset_recommended="Elige DAT que coincida con J64/ROM/ABS/COF; Jaguar sigue marcado experimental.",
        ra_console_id=17,
        complexity="experimental",
        notes="Variantes ABS/COF/J64 requieren validacion cuidadosa.",
    ),
    Platform.NGP: PlatformSpec(
        id=Platform.NGP,
        name="Neo Geo Pocket",
        short_name="Neo Geo Pocket",
        brand="SNK",
        generation="portatil clasica",
        kind="portatil",
        icon="view_week",
        color="teal",
        extensions=(".ngp", ".bin", ".zip"),
        rom_extensions=(".ngp", ".bin"),
        dat_aliases=("SNK - Neo Geo Pocket",),
        dat_recommended="No-Intro Parent/Clone XML",
        ra_console_id=14,
    ),
    Platform.NGPC: PlatformSpec(
        id=Platform.NGPC,
        name="Neo Geo Pocket Color",
        short_name="NGP Color",
        brand="SNK",
        generation="portatil clasica",
        kind="portatil",
        icon="view_carousel",
        color="teal",
        extensions=(".ngc", ".ngp", ".bin", ".zip"),
        rom_extensions=(".ngc", ".ngp", ".bin"),
        dat_aliases=("SNK - Neo Geo Pocket Color",),
        dat_recommended="No-Intro Parent/Clone XML",
        ra_console_id=82,
    ),
    Platform.WS: PlatformSpec(
        id=Platform.WS,
        name="WonderSwan",
        short_name="WonderSwan",
        brand="Bandai",
        generation="portatil clasica",
        kind="portatil",
        icon="crop_portrait",
        color="pink",
        extensions=(".ws", ".bin", ".zip"),
        rom_extensions=(".ws", ".bin"),
        dat_aliases=("Bandai - WonderSwan",),
        dat_recommended="No-Intro Parent/Clone XML",
        ra_console_id=45,
    ),
    Platform.WSC: PlatformSpec(
        id=Platform.WSC,
        name="WonderSwan Color",
        short_name="WonderSwan Color",
        brand="Bandai",
        generation="portatil clasica",
        kind="portatil",
        icon="crop_16_9",
        color="pink",
        extensions=(".wsc", ".ws", ".bin", ".zip"),
        rom_extensions=(".wsc", ".ws", ".bin"),
        dat_aliases=("Bandai - WonderSwan Color",),
        dat_recommended="No-Intro Parent/Clone XML",
        ra_console_id=46,
    ),
    Platform.COLECO: PlatformSpec(
        id=Platform.COLECO,
        name="ColecoVision",
        short_name="ColecoVision",
        brand="Otros",
        generation="2a gen",
        kind="sobremesa",
        icon="apps",
        color="green",
        extensions=(".col", ".rom", ".bin", ".zip"),
        rom_extensions=(".col", ".rom", ".bin"),
        dat_aliases=("Coleco - ColecoVision",),
        dat_recommended="No-Intro Parent/Clone XML",
        ra_console_id=44,
    ),
    Platform.INTV: PlatformSpec(
        id=Platform.INTV,
        name="Intellivision",
        short_name="Intellivision",
        brand="Otros",
        generation="2a gen",
        kind="sobremesa",
        icon="dialpad",
        color="deep-orange",
        extensions=(".int", ".bin", ".rom", ".zip"),
        rom_extensions=(".int", ".bin", ".rom"),
        dat_aliases=("Mattel - Intellivision",),
        dat_recommended="No-Intro Parent/Clone XML",
        ra_console_id=32,
    ),
    Platform.VECTREX: PlatformSpec(
        id=Platform.VECTREX,
        name="Vectrex",
        short_name="Vectrex",
        brand="Otros",
        generation="2a gen",
        kind="sobremesa",
        icon="timeline",
        color="black",
        extensions=(".vec", ".bin", ".zip"),
        rom_extensions=(".vec", ".bin"),
        dat_aliases=("GCE - Vectrex",),
        dat_recommended="No-Intro Parent/Clone XML",
        ra_console_id=102,
    ),
    Platform.ODYSSEY2: PlatformSpec(
        id=Platform.ODYSSEY2,
        name="Odyssey2 / Videopac+",
        short_name="Odyssey2",
        brand="Otros",
        generation="2a gen",
        kind="sobremesa",
        icon="select_all",
        color="amber",
        extensions=(".bin", ".zip"),
        rom_extensions=(".bin",),
        dat_aliases=("Magnavox - Odyssey2", "Philips - Videopac+"),
        dat_recommended="No-Intro Parent/Clone XML",
        ra_console_id=23,
    ),
    Platform.POKEMON_MINI: PlatformSpec(
        id=Platform.POKEMON_MINI,
        name="Pokemon Mini",
        short_name="Pokemon Mini",
        brand="Nintendo",
        generation="portatil clasica",
        kind="portatil",
        icon="catching_pokemon",
        color="yellow",
        extensions=(".min", ".bin", ".zip"),
        rom_extensions=(".min", ".bin"),
        dat_aliases=("Nintendo - Pokemon Mini",),
        dat_recommended="No-Intro Parent/Clone XML",
        complexity="simple",
    ),
    Platform.SATELLAVIEW: PlatformSpec(
        id=Platform.SATELLAVIEW,
        name="Satellaview",
        short_name="Satellaview",
        brand="Nintendo",
        generation="4a gen",
        kind="sobremesa",
        icon="satellite_alt",
        color="purple",
        extensions=(".bs", ".sfc", ".smc", ".zip"),
        rom_extensions=(".bs", ".sfc", ".smc"),
        dat_aliases=("Nintendo - Satellaview",),
        dat_recommended="No-Intro Parent/Clone XML",
        hash_mode="snes",
        complexity="especial",
    ),
    Platform.SUFAMI_TURBO: PlatformSpec(
        id=Platform.SUFAMI_TURBO,
        name="Sufami Turbo",
        short_name="Sufami Turbo",
        brand="Nintendo",
        generation="4a gen",
        kind="sobremesa",
        icon="join_inner",
        color="purple",
        extensions=(".st", ".sfc", ".zip"),
        rom_extensions=(".st", ".sfc"),
        dat_aliases=("Nintendo - Sufami Turbo",),
        dat_recommended="No-Intro Parent/Clone XML",
        hash_mode="snes",
        complexity="especial",
    ),
    Platform.EREADER: PlatformSpec(
        id=Platform.EREADER,
        name="e-Reader",
        short_name="e-Reader",
        brand="Nintendo",
        generation="6a gen",
        kind="portatil",
        icon="view_agenda",
        color="deep-purple",
        extensions=(".bin", ".raw", ".zip"),
        rom_extensions=(".bin", ".raw"),
        dat_aliases=("Nintendo - e-Reader",),
        dat_recommended="No-Intro Parent/Clone XML",
        complexity="experimental",
    ),
    Platform.PICO: PlatformSpec(
        id=Platform.PICO,
        name="Sega Pico",
        short_name="Pico",
        brand="Sega",
        generation="4a gen",
        kind="sobremesa",
        icon="menu_book",
        color="blue",
        extensions=(".bin", ".md", ".zip"),
        rom_extensions=(".bin", ".md"),
        dat_aliases=("Sega - Pico",),
        dat_recommended="No-Intro Parent/Clone XML",
        complexity="especial",
    ),
    Platform.BEENA: PlatformSpec(
        id=Platform.BEENA,
        name="Advanced Pico Beena",
        short_name="Beena",
        brand="Sega",
        generation="6a gen",
        kind="sobremesa",
        icon="auto_stories",
        color="blue",
        extensions=(".bin", ".zip"),
        rom_extensions=(".bin",),
        dat_aliases=("Sega - Advanced Pico Beena",),
        dat_recommended="No-Intro Parent/Clone XML",
        complexity="experimental",
    ),
    Platform.DREAMCAST_VMU: PlatformSpec(
        id=Platform.DREAMCAST_VMU,
        name="Dreamcast VMU",
        short_name="Dreamcast VMU",
        brand="Sega",
        generation="6a gen",
        kind="portatil",
        icon="memory",
        color="blue",
        extensions=(".vms", ".bin", ".zip"),
        rom_extensions=(".vms", ".bin"),
        dat_aliases=("Sega - Dreamcast VMU",),
        dat_recommended="No-Intro Parent/Clone XML",
        complexity="experimental",
    ),
    Platform.GAMECOM: PlatformSpec(
        id=Platform.GAMECOM,
        name="Game.com",
        short_name="Game.com",
        brand="Otros",
        generation="5a gen",
        kind="portatil",
        icon="grid_view",
        color="grey",
        extensions=(".bin", ".tgc", ".zip"),
        rom_extensions=(".bin", ".tgc"),
        dat_aliases=("Tiger - Game.com",),
        dat_recommended="No-Intro Parent/Clone XML",
        complexity="simple",
    ),
    Platform.SUPERVISION: PlatformSpec(
        id=Platform.SUPERVISION,
        name="Watara Supervision",
        short_name="Supervision",
        brand="Otros",
        generation="portatil clasica",
        kind="portatil",
        icon="crop_7_5",
        color="grey",
        extensions=(".sv", ".bin", ".zip"),
        rom_extensions=(".sv", ".bin"),
        dat_aliases=("Watara - Supervision",),
        dat_recommended="No-Intro Parent/Clone XML",
        complexity="simple",
    ),
    Platform.MEGA_DUCK: PlatformSpec(
        id=Platform.MEGA_DUCK,
        name="Mega Duck / Cougar Boy",
        short_name="Mega Duck",
        brand="Otros",
        generation="portatil clasica",
        kind="portatil",
        icon="view_stream",
        color="amber",
        extensions=(".bin", ".zip"),
        rom_extensions=(".bin",),
        dat_aliases=("Welback - Mega Duck", "Creatronic - Mega Duck"),
        dat_recommended="No-Intro Parent/Clone XML",
        complexity="simple",
    ),
    Platform.GAMATE: PlatformSpec(
        id=Platform.GAMATE,
        name="Gamate",
        short_name="Gamate",
        brand="Otros",
        generation="portatil clasica",
        kind="portatil",
        icon="crop_5_4",
        color="grey",
        extensions=(".bin", ".zip"),
        rom_extensions=(".bin",),
        dat_aliases=("Bit Corp - Gamate",),
        dat_recommended="No-Intro Parent/Clone XML",
        complexity="simple",
    ),
    Platform.GP32: PlatformSpec(
        id=Platform.GP32,
        name="GP32",
        short_name="GP32",
        brand="Otros",
        generation="6a gen",
        kind="portatil",
        icon="perm_device_information",
        color="grey",
        extensions=(".fxe", ".gxb", ".bin", ".zip"),
        rom_extensions=(".fxe", ".gxb", ".bin"),
        dat_aliases=("GamePark - GP32",),
        dat_recommended="No-Intro Parent/Clone XML",
        complexity="experimental",
    ),
    Platform.LOOPY: PlatformSpec(
        id=Platform.LOOPY,
        name="Casio Loopy",
        short_name="Loopy",
        brand="Otros",
        generation="5a gen",
        kind="sobremesa",
        icon="print",
        color="pink",
        extensions=(".bin", ".zip"),
        rom_extensions=(".bin",),
        dat_aliases=("Casio - Loopy",),
        dat_recommended="No-Intro Parent/Clone XML",
        complexity="simple",
    ),
    Platform.PV1000: PlatformSpec(
        id=Platform.PV1000,
        name="Casio PV-1000",
        short_name="PV-1000",
        brand="Otros",
        generation="2a gen",
        kind="sobremesa",
        icon="developer_mode",
        color="grey",
        extensions=(".bin", ".zip"),
        rom_extensions=(".bin",),
        dat_aliases=("Casio - PV-1000",),
        dat_recommended="No-Intro Parent/Clone XML",
        complexity="simple",
    ),
    Platform.ARCADIA: PlatformSpec(
        id=Platform.ARCADIA,
        name="Arcadia 2001",
        short_name="Arcadia 2001",
        brand="Otros",
        generation="2a gen",
        kind="sobremesa",
        icon="widgets",
        color="grey",
        extensions=(".bin", ".zip"),
        rom_extensions=(".bin",),
        dat_aliases=("Emerson - Arcadia 2001",),
        dat_recommended="No-Intro Parent/Clone XML",
        complexity="simple",
    ),
    Platform.CHANNELF: PlatformSpec(
        id=Platform.CHANNELF,
        name="Fairchild Channel F",
        short_name="Channel F",
        brand="Otros",
        generation="2a gen",
        kind="sobremesa",
        icon="view_quilt",
        color="grey",
        extensions=(".bin", ".chf", ".zip"),
        rom_extensions=(".bin", ".chf"),
        dat_aliases=("Fairchild - Channel F",),
        dat_recommended="No-Intro Parent/Clone XML",
        complexity="simple",
    ),
    Platform.SUPERCASSETTE: PlatformSpec(
        id=Platform.SUPERCASSETTE,
        name="Super Cassette Vision",
        short_name="Super Cassette Vision",
        brand="Otros",
        generation="3a gen",
        kind="sobremesa",
        icon="view_array",
        color="grey",
        extensions=(".bin", ".zip"),
        rom_extensions=(".bin",),
        dat_aliases=("Epoch - Super Cassette Vision",),
        dat_recommended="No-Intro Parent/Clone XML",
        complexity="simple",
    ),
    Platform.CREATIVISION: PlatformSpec(
        id=Platform.CREATIVISION,
        name="CreatiVision",
        short_name="CreatiVision",
        brand="Otros",
        generation="2a gen",
        kind="sobremesa",
        icon="keyboard",
        color="grey",
        extensions=(".bin", ".rom", ".zip"),
        rom_extensions=(".bin", ".rom"),
        dat_aliases=("VTech - CreatiVision",),
        dat_recommended="No-Intro Parent/Clone XML",
        complexity="simple",
    ),
    Platform.VSMILE: PlatformSpec(
        id=Platform.VSMILE,
        name="V.Smile",
        short_name="V.Smile",
        brand="Otros",
        generation="6a gen",
        kind="sobremesa",
        icon="school",
        color="green",
        extensions=(".bin", ".zip"),
        rom_extensions=(".bin",),
        dat_aliases=("VTech - V.Smile",),
        dat_recommended="No-Intro Parent/Clone XML",
        complexity="experimental",
    ),
    Platform.LEAPSTER: PlatformSpec(
        id=Platform.LEAPSTER,
        name="Leapster",
        short_name="Leapster",
        brand="Otros",
        generation="6a gen",
        kind="portatil",
        icon="child_care",
        color="green",
        extensions=(".bin", ".zip"),
        rom_extensions=(".bin",),
        dat_aliases=("LeapFrog - Leapster Learning Game System",),
        dat_recommended="No-Intro Parent/Clone XML",
        complexity="experimental",
    ),
    Platform.ARDUBOY: PlatformSpec(
        id=Platform.ARDUBOY,
        name="Arduboy",
        short_name="Arduboy",
        brand="Otros",
        generation="experimental",
        kind="experimental",
        icon="code",
        color="blue-grey",
        extensions=(".hex", ".bin", ".zip"),
        rom_extensions=(".hex", ".bin"),
        dat_aliases=("Arduboy Inc - Arduboy",),
        dat_recommended="No-Intro Parent/Clone XML",
        complexity="experimental",
    ),
    Platform.MSX: PlatformSpec(
        id=Platform.MSX,
        name="MSX cartridges",
        short_name="MSX",
        brand="Otros",
        generation="3a gen",
        kind="ordenador",
        icon="desktop_windows",
        color="blue-grey",
        extensions=(".rom", ".mx1", ".bin", ".zip"),
        rom_extensions=(".rom", ".mx1", ".bin"),
        dat_aliases=("Microsoft - MSX",),
        dat_recommended="No-Intro cartridge ROM DAT",
        romset_recommended="Solo cartuchos ROM para esta fase; no mezclar discos/cintas.",
        complexity="especial",
        notes="Solo cartuchos ROM en esta fase; discos/cintas quedan para adaptador posterior.",
    ),
    Platform.MSX2: PlatformSpec(
        id=Platform.MSX2,
        name="MSX2 cartridges",
        short_name="MSX2",
        brand="Otros",
        generation="3a gen",
        kind="ordenador",
        icon="desktop_mac",
        color="blue-grey",
        extensions=(".rom", ".mx2", ".bin", ".zip"),
        rom_extensions=(".rom", ".mx2", ".bin"),
        dat_aliases=("Microsoft - MSX2",),
        dat_recommended="No-Intro cartridge ROM DAT",
        romset_recommended="Solo cartuchos ROM para esta fase; no mezclar discos/cintas.",
        complexity="especial",
        notes="Solo cartuchos ROM en esta fase; discos/cintas quedan para adaptador posterior.",
    ),
    Platform.C64: PlatformSpec(
        id=Platform.C64,
        name="Commodore 64",
        short_name="C64",
        brand="Otros",
        generation="3a gen",
        kind="ordenador",
        icon="computer",
        color="brown",
        extensions=(".crt", ".prg", ".d64", ".t64", ".tap", ".zip"),
        rom_extensions=(".crt", ".prg", ".d64", ".t64", ".tap"),
        dat_aliases=("Commodore - 64", "Commodore - Commodore 64"),
        dat_recommended="No-Intro DAT por tipo de medio",
        romset_recommended="Separar cartuchos, discos y cintas; no mezclar medios en un 1G1R único.",
        collection_tip="Experimental: los ordenadores necesitan reglas por medio y multidisco.",
        complexity="experimental",
    ),
    Platform.AMIGA: PlatformSpec(
        id=Platform.AMIGA,
        name="Commodore Amiga",
        short_name="Amiga",
        brand="Otros",
        generation="4a gen",
        kind="ordenador",
        icon="desktop_windows",
        color="brown",
        extensions=(".adf", ".ipf", ".hdf", ".lha", ".zip"),
        rom_extensions=(".adf", ".ipf", ".hdf", ".lha"),
        dat_aliases=("Commodore - Amiga",),
        dat_recommended="No-Intro/TOSEC según medio",
        romset_recommended="Mantener ADF/IPF/LHA separados; WHDLoad/LHA requiere flujo propio.",
        collection_tip="Experimental: multidisco y compilaciones requieren decisiones manuales.",
        complexity="experimental",
    ),
    Platform.ATARI_ST: PlatformSpec(
        id=Platform.ATARI_ST,
        name="Atari ST",
        short_name="Atari ST",
        brand="Atari",
        generation="4a gen",
        kind="ordenador",
        icon="desktop_mac",
        color="brown",
        extensions=(".st", ".msa", ".ipf", ".zip"),
        rom_extensions=(".st", ".msa", ".ipf"),
        dat_aliases=("Atari - ST",),
        dat_recommended="No-Intro DAT por formato",
        romset_recommended="No mezclar ST/MSA/IPF sin confirmar DAT.",
        collection_tip="Experimental: multidisco necesita agrupación más rica.",
        complexity="experimental",
    ),
    Platform.ATARI_8BIT: PlatformSpec(
        id=Platform.ATARI_8BIT,
        name="Atari 8-bit",
        short_name="Atari 8-bit",
        brand="Atari",
        generation="3a gen",
        kind="ordenador",
        icon="keyboard_alt",
        color="brown",
        extensions=(".rom", ".car", ".xex", ".atr", ".zip"),
        rom_extensions=(".rom", ".car", ".xex", ".atr"),
        dat_aliases=("Atari - 8-bit",),
        dat_recommended="No-Intro DAT por tipo de medio",
        romset_recommended="Cartuchos/ejecutables/discos separados.",
        collection_tip="Experimental: medios mixtos no deben curarse con una sola regla.",
        complexity="experimental",
    ),
    Platform.CPC: PlatformSpec(
        id=Platform.CPC,
        name="Amstrad CPC",
        short_name="Amstrad CPC",
        brand="Otros",
        generation="3a gen",
        kind="ordenador",
        icon="keyboard",
        color="blue-grey",
        extensions=(".dsk", ".cdt", ".cpr", ".zip"),
        rom_extensions=(".dsk", ".cdt", ".cpr"),
        dat_aliases=("Amstrad - CPC",),
        dat_recommended="No-Intro DAT por medio",
        romset_recommended="Separar discos, cintas y cartuchos.",
        collection_tip="Experimental: prioridad por región suele importar menos que medio/versión.",
        complexity="experimental",
    ),
    Platform.ZX_SPECTRUM: PlatformSpec(
        id=Platform.ZX_SPECTRUM,
        name="ZX Spectrum",
        short_name="ZX Spectrum",
        brand="Otros",
        generation="3a gen",
        kind="ordenador",
        icon="keyboard_command_key",
        color="blue-grey",
        extensions=(".tap", ".tzx", ".z80", ".sna", ".dsk", ".zip"),
        rom_extensions=(".tap", ".tzx", ".z80", ".sna", ".dsk"),
        dat_aliases=("Sinclair - ZX Spectrum",),
        dat_recommended="No-Intro DAT por medio",
        romset_recommended="Separar snapshots, cintas y discos.",
        collection_tip="Experimental: snapshots no equivalen siempre a preservación de cinta/disco.",
        complexity="experimental",
    ),
    Platform.APPLE_II: PlatformSpec(
        id=Platform.APPLE_II,
        name="Apple II",
        short_name="Apple II",
        brand="Otros",
        generation="2a gen",
        kind="ordenador",
        icon="laptop_mac",
        color="grey",
        extensions=(".dsk", ".do", ".po", ".woz", ".a2r", ".zip"),
        rom_extensions=(".dsk", ".do", ".po", ".woz", ".a2r"),
        dat_aliases=("Apple - II", "Apple - Apple II"),
        dat_recommended="No-Intro DAT por formato",
        romset_recommended="WOZ/A2R preservación avanzada; DSK/DO/PO por separado.",
        collection_tip="Experimental: flux/bitstream necesita reglas propias.",
        complexity="experimental",
    ),
    Platform.X68000: PlatformSpec(
        id=Platform.X68000,
        name="Sharp X68000",
        short_name="X68000",
        brand="Otros",
        generation="4a gen",
        kind="ordenador",
        icon="desktop_windows",
        color="blue-grey",
        extensions=(".dim", ".hdf", ".xdf", ".zip"),
        rom_extensions=(".dim", ".hdf", ".xdf"),
        dat_aliases=("Sharp - X68000",),
        dat_recommended="No-Intro DAT por formato",
        romset_recommended="Separar discos y discos duros.",
        collection_tip="Experimental: multidisco y HDD requieren agrupación especial.",
        complexity="experimental",
    ),
    Platform.PC88: PlatformSpec(
        id=Platform.PC88,
        name="NEC PC-88",
        short_name="PC-88",
        brand="NEC",
        generation="3a gen",
        kind="ordenador",
        icon="desktop_windows",
        color="orange",
        extensions=(".d88", ".fdi", ".hdi", ".zip"),
        rom_extensions=(".d88", ".fdi", ".hdi"),
        dat_aliases=("NEC - PC-88",),
        dat_recommended="No-Intro DAT por formato",
        romset_recommended="Separar floppy y hard disk.",
        collection_tip="Experimental: multidisco necesita soporte específico.",
        complexity="experimental",
    ),
    Platform.PC98: PlatformSpec(
        id=Platform.PC98,
        name="NEC PC-98",
        short_name="PC-98",
        brand="NEC",
        generation="4a gen",
        kind="ordenador",
        icon="desktop_windows",
        color="orange",
        extensions=(".fdi", ".hdi", ".d88", ".zip"),
        rom_extensions=(".fdi", ".hdi", ".d88"),
        dat_aliases=("NEC - PC-98",),
        dat_recommended="No-Intro DAT por formato",
        romset_recommended="Separar floppy y hard disk.",
        collection_tip="Experimental: multidisco necesita soporte específico.",
        complexity="experimental",
    ),
    Platform.TI99: PlatformSpec(
        id=Platform.TI99,
        name="TI-99/4A",
        short_name="TI-99/4A",
        brand="Otros",
        generation="2a gen",
        kind="ordenador",
        icon="calculate",
        color="grey",
        extensions=(".bin", ".rpk", ".zip"),
        rom_extensions=(".bin", ".rpk"),
        dat_aliases=("Texas Instruments - TI-99-4A",),
        dat_recommended="No-Intro cartridge DAT",
        romset_recommended="Preferir cartuchos/RPK separados de otros medios.",
        complexity="experimental",
    ),
    Platform.NGAGE: PlatformSpec(
        id=Platform.NGAGE,
        name="N-Gage",
        short_name="N-Gage",
        brand="Otros",
        generation="6a gen",
        kind="portatil",
        icon="phone_android",
        color="green",
        extensions=(".zip", ".sis", ".ngage"),
        rom_extensions=(".sis", ".ngage"),
        dat_aliases=("Nokia - N-Gage",),
        dat_recommended="No-Intro WIP DAT",
        romset_recommended="WIP: validar manualmente fuente y formato.",
        collection_tip="Experimental: instalación/contenido móvil no siempre es una ROM simple.",
        complexity="experimental",
    ),
    Platform.GIZMONDO: PlatformSpec(
        id=Platform.GIZMONDO,
        name="Gizmondo",
        short_name="Gizmondo",
        brand="Otros",
        generation="6a gen",
        kind="portatil",
        icon="phone_android",
        color="grey",
        extensions=(".zip", ".bin"),
        rom_extensions=(".bin",),
        dat_aliases=("Tiger - Gizmondo",),
        dat_recommended="No-Intro DAT",
        complexity="experimental",
    ),
    Platform.NUON: PlatformSpec(
        id=Platform.NUON,
        name="Nuon",
        short_name="Nuon",
        brand="Otros",
        generation="6a gen",
        kind="sobremesa",
        icon="album",
        color="grey",
        extensions=(".bin", ".iso", ".zip"),
        rom_extensions=(".bin", ".iso"),
        dat_aliases=("VM Labs - NUON",),
        dat_recommended="No-Intro/Redump según medio",
        romset_recommended="Disco/ISO requiere flujo tipo Redump más adelante.",
        complexity="experimental",
    ),
    Platform.IQUE: PlatformSpec(
        id=Platform.IQUE,
        name="iQue",
        short_name="iQue",
        brand="Nintendo",
        generation="6a gen",
        kind="digital",
        icon="cloud_download",
        color="red",
        extensions=(".bin", ".app", ".zip"),
        rom_extensions=(".bin", ".app"),
        dat_aliases=("Nintendo - iQue",),
        dat_recommended="No-Intro CDN/Decrypted según romset",
        romset_recommended="Digital/CDN y decrypted separados.",
        collection_tip="Experimental: requiere flujo digital propio.",
        complexity="experimental",
    ),
    Platform.ZEEBO: PlatformSpec(
        id=Platform.ZEEBO,
        name="Zeebo",
        short_name="Zeebo",
        brand="Otros",
        generation="7a gen",
        kind="digital",
        icon="cloud",
        color="blue-grey",
        extensions=(".bin", ".zip"),
        rom_extensions=(".bin",),
        dat_aliases=("Tectoy - Zeebo",),
        dat_recommended="No-Intro DAT",
        collection_tip="Experimental: distribución digital requiere revisión manual.",
        complexity="experimental",
    ),
    Platform.PIPPIN: PlatformSpec(
        id=Platform.PIPPIN,
        name="Apple Pippin",
        short_name="Pippin",
        brand="Otros",
        generation="5a gen",
        kind="sobremesa",
        icon="album",
        color="grey",
        extensions=(".bin", ".iso", ".zip"),
        rom_extensions=(".bin", ".iso"),
        dat_aliases=("Apple - Pippin",),
        dat_recommended="No-Intro/Redump según medio",
        romset_recommended="Disco/ISO requiere flujo tipo Redump más adelante.",
        complexity="experimental",
    ),
}


PRIORITY_PLATFORMS: tuple[Platform, ...] = (
    Platform.NES,
    Platform.FDS,
    Platform.SNES,
    Platform.GB,
    Platform.GBC,
    Platform.GBA,
    Platform.VB,
    Platform.N64,
    Platform.NDS,
    Platform.SMS,
    Platform.GG,
    Platform.MD,
    Platform.S32X,
    Platform.SG1000,
    Platform.PCE,
    Platform.SGX,
    Platform.A2600,
    Platform.A5200,
    Platform.A7800,
    Platform.LYNX,
    Platform.JAGUAR,
    Platform.NGP,
    Platform.NGPC,
    Platform.WS,
    Platform.WSC,
    Platform.COLECO,
    Platform.INTV,
    Platform.VECTREX,
    Platform.ODYSSEY2,
    Platform.POKEMON_MINI,
    Platform.SATELLAVIEW,
    Platform.SUFAMI_TURBO,
    Platform.EREADER,
    Platform.PICO,
    Platform.BEENA,
    Platform.DREAMCAST_VMU,
    Platform.GAMECOM,
    Platform.SUPERVISION,
    Platform.MEGA_DUCK,
    Platform.GAMATE,
    Platform.GP32,
    Platform.LOOPY,
    Platform.PV1000,
    Platform.ARCADIA,
    Platform.CHANNELF,
    Platform.SUPERCASSETTE,
    Platform.CREATIVISION,
    Platform.VSMILE,
    Platform.LEAPSTER,
    Platform.ARDUBOY,
    Platform.MSX,
    Platform.MSX2,
    Platform.C64,
    Platform.AMIGA,
    Platform.ATARI_ST,
    Platform.ATARI_8BIT,
    Platform.CPC,
    Platform.ZX_SPECTRUM,
    Platform.APPLE_II,
    Platform.X68000,
    Platform.PC88,
    Platform.PC98,
    Platform.TI99,
    Platform.NGAGE,
    Platform.GIZMONDO,
    Platform.NUON,
    Platform.IQUE,
    Platform.ZEEBO,
    Platform.PIPPIN,
)


def _spec(
    id: Platform,
    name: str,
    short_name: str,
    brand: str,
    generation: str,
    kind: str,
    icon: str,
    color: str,
    extensions: tuple[str, ...],
    dat_aliases: tuple[str, ...],
    dat_recommended: str,
    *,
    rom_extensions: tuple[str, ...] | None = None,
    dat_family: str = "nointro",
    romset_recommended: str | None = None,
    collection_tip: str | None = None,
    hash_mode: str = "direct",
    ra_console_id: int | None = None,
    ra_active: bool = True,
    complexity: str = "experimental",
    notes: str = "",
) -> PlatformSpec:
    return PlatformSpec(
        id=id,
        name=name,
        short_name=short_name,
        brand=brand,
        generation=generation,
        kind=kind,
        icon=icon,
        color=color,
        extensions=extensions,
        rom_extensions=rom_extensions or tuple(ext for ext in extensions if ext not in {".zip", ".7z", ".rar"}),
        dat_aliases=dat_aliases,
        dat_recommended=dat_recommended,
        dat_family=dat_family,
        romset_recommended=romset_recommended or "Romset que coincida exactamente con el DAT elegido.",
        collection_tip=collection_tip or "Soporte inicial por DAT: escaneo, informe y exportacion. Algunas variantes requieren reglas especificas.",
        hash_mode=hash_mode,
        ra_console_id=ra_console_id,
        ra_active=ra_active,
        complexity=complexity,
        notes=notes,
    )


CD_EXTENSIONS = (".cue", ".bin", ".iso", ".chd", ".gdi", ".cdi", ".zip", ".7z")
DISK_EXTENSIONS = (".dsk", ".do", ".po", ".woz", ".a2r", ".adf", ".ipf", ".hdf", ".d88", ".fdi", ".hdi", ".dim", ".xdf", ".zip", ".7z")
DIGITAL_EXTENSIONS = (".app", ".cia", ".tik", ".tmd", ".nds", ".wad", ".pkg", ".rap", ".nsp", ".xci", ".zip", ".7z")
ARCADE_EXTENSIONS = (".zip", ".7z", ".chd")


_EXTRA_SPECS: tuple[PlatformSpec, ...] = (
    _spec(Platform.N64DD, "Nintendo 64DD", "N64DD", "Nintendo", "5a gen", "sobremesa", "album", "green", (".ndd", ".n64", ".zip", ".7z"), ("Nintendo - Nintendo 64DD",), "No-Intro Parent/Clone XML", romset_recommended="No-Intro N64DD del mismo formato que el DAT.", complexity="especial"),
    _spec(Platform.NDS_DOWNLOAD_PLAY, "Nintendo DS Download Play", "DS Download Play", "Nintendo", "7a gen", "digital", "wifi_tethering", "blue", (".nds", ".srl", ".zip"), ("Nintendo - Nintendo DS (Download Play)",), "No-Intro Standard DAT", complexity="especial"),
    _spec(Platform.DSI, "Nintendo DSi", "Nintendo DSi", "Nintendo", "7a gen", "portatil", "filter_none", "blue", (".nds", ".srl", ".zip"), ("Nintendo - Nintendo DSi",), "No-Intro Parent/Clone XML", complexity="especial"),
    _spec(Platform.DSIWARE, "Nintendo DSiWare", "DSiWare", "Nintendo", "7a gen", "digital", "apps", "blue", DIGITAL_EXTENSIONS, ("Nintendo - Nintendo DSi (Digital)",), "No-Intro Digital/CDN DAT", complexity="experimental"),
    _spec(Platform.DSI_CDN, "Nintendo DSi Digital CDN", "DSi CDN", "Nintendo", "7a gen", "digital", "cloud_download", "blue", DIGITAL_EXTENSIONS, ("Nintendo - Nintendo DSi (Digital) (CDN)",), "No-Intro CDN DAT", complexity="experimental"),
    _spec(Platform.N3DS, "New Nintendo 3DS", "New 3DS", "Nintendo", "8a gen", "portatil", "filter_none", "red", (".3ds", ".cci", ".cia", ".zip", ".7z"), ("Nintendo - New Nintendo 3DS",), "No-Intro decrypted/standard DAT", complexity="especial"),
    _spec(Platform.N3DS_DIGITAL, "New Nintendo 3DS Digital", "New 3DS Digital", "Nintendo", "8a gen", "digital", "cloud_download", "red", DIGITAL_EXTENSIONS, ("Nintendo - New Nintendo 3DS (Digital)",), "No-Intro CDN/Digital DAT", complexity="experimental"),
    _spec(Platform.N3DS_DLC, "New Nintendo 3DS DLC", "New 3DS DLC", "Nintendo", "8a gen", "digital", "extension", "red", DIGITAL_EXTENSIONS, ("Nintendo - New Nintendo 3DS (Digital) (Deprecated)",), "No-Intro Digital DLC DAT", complexity="experimental"),
    _spec(Platform.N3DS_DEV, "New Nintendo 3DS Dev ROMs", "New 3DS Dev", "Nintendo", "8a gen", "experimental", "bug_report", "red", DIGITAL_EXTENSIONS, ("Nintendo - Nintendo 3DS (Digital) (Dev ROMs)",), "No-Intro Dev ROM DAT", complexity="experimental"),
    _spec(Platform.N3DS_PREINSTALL, "Nintendo 3DS Pre-Install", "3DS Pre-Install", "Nintendo", "8a gen", "digital", "inventory", "red", DIGITAL_EXTENSIONS, ("Nintendo - Nintendo 3DS (Digital) (Pre-Install)",), "No-Intro Pre-Install DAT", complexity="experimental"),
    _spec(Platform.N3DS_CIA, "Nintendo 3DS Updates and DLC", "3DS CIA/DLC", "Nintendo", "8a gen", "digital", "system_update_alt", "red", DIGITAL_EXTENSIONS, ("Unofficial - Nintendo - Nintendo 3DS (Digital) (Updates and DLC)",), "No-Intro/Unofficial CIA DAT", complexity="experimental"),
    _spec(Platform.GAME_WATCH, "Nintendo Game & Watch", "Game & Watch", "Nintendo", "2a gen", "portatil", "watch", "red", (".bin", ".mgw", ".zip"), ("Nintendo - Game & Watch",), "No-Intro Standard DAT"),
    _spec(Platform.FAMILY_BASIC, "Nintendo Family BASIC", "Family BASIC", "Nintendo", "3a gen", "sobremesa", "keyboard", "red", (".nes", ".bin", ".zip"), ("Nintendo - Family BASIC",), "No-Intro Standard DAT"),
    _spec(Platform.FAMICOM_NETWORK, "Famicom Network System", "Famicom Network", "Nintendo", "3a gen", "digital", "hub", "red", (".bin", ".nes", ".zip"), ("Nintendo - Family Computer Network System",), "No-Intro Standard DAT"),
    _spec(Platform.KIOSK_CF, "Nintendo Kiosk Video Compact Flash", "Nintendo Kiosk CF", "Nintendo", "6a gen", "digital", "sd_card", "red", (".bin", ".img", ".zip", ".7z"), ("Nintendo - Kiosk Video Compact Flash",), "No-Intro Compact Flash DAT", complexity="experimental"),
    _spec(Platform.MARIO_PHOTOPI, "Mario no Photopi SmartMedia", "Mario Photopi", "Nintendo", "5a gen", "digital", "photo_camera", "red", (".bin", ".img", ".zip"), ("Nintendo - Mario no Photopi SmartMedia",), "No-Intro SmartMedia DAT", complexity="experimental"),
    _spec(Platform.NINTENDO_MISC, "Nintendo Misc", "Nintendo Misc", "Nintendo", "varios", "experimental", "category", "red", (".bin", ".dat", ".zip", ".7z"), ("Nintendo - Misc",), "No-Intro Misc DAT", complexity="experimental"),
    _spec(Platform.PLAY_YAN, "Nintendo Play-Yan", "Play-Yan", "Nintendo", "6a gen", "digital", "play_circle", "red", (".bin", ".gba", ".zip"), ("Nintendo - Play-Yan",), "No-Intro Standard DAT", complexity="experimental"),
    _spec(Platform.AMIIBO, "Nintendo amiibo", "amiibo", "Nintendo", "8a gen", "digital", "nfc", "red", (".bin", ".zip"), ("Nintendo - amiibo",), "No-Intro amiibo DAT", complexity="experimental"),
    _spec(Platform.SWITCH, "Nintendo Switch", "Switch", "Nintendo", "8a gen", "digital", "tablet_mac", "red", (".xci", ".nsp", ".nca", ".zip", ".7z"), ("Nintendo - Nintendo Switch",), "No-Intro Switch DAT", complexity="experimental", notes="Puede incluir DATs logged-in-only; no se automatiza descarga privada."),
    _spec(Platform.SWITCH_DIGITAL, "Nintendo Switch Digital", "Switch Digital", "Nintendo", "8a gen", "digital", "cloud_download", "red", (".nsp", ".nca", ".tik", ".zip", ".7z"), ("Nintendo - Nintendo Switch (Digital)",), "No-Intro Switch Digital DAT", complexity="experimental", notes="Puede incluir DATs logged-in-only."),
    _spec(Platform.SWITCH_DLC, "Nintendo Switch DLC", "Switch DLC", "Nintendo", "8a gen", "digital", "extension", "red", (".nsp", ".nca", ".zip", ".7z"), ("Nintendo - Nintendo Switch (Digital) (DLC)",), "No-Intro Switch DLC DAT", complexity="experimental"),
    _spec(Platform.WII_CDN, "Nintendo Wii Digital CDN", "Wii CDN", "Nintendo", "7a gen", "digital", "cloud_download", "blue", (".wad", ".app", ".tik", ".tmd", ".zip", ".7z"), ("Nintendo - Wii (Digital) (CDN)",), "No-Intro CDN DAT", complexity="experimental"),
    _spec(Platform.WIIU_CDN, "Nintendo Wii U Digital CDN", "Wii U CDN", "Nintendo", "8a gen", "digital", "cloud_download", "blue", (".app", ".tik", ".tmd", ".wud", ".wux", ".zip", ".7z"), ("Nintendo - Wii U (Digital) (CDN)",), "No-Intro CDN DAT", complexity="experimental"),
    _spec(Platform.WIIU_DLC, "Nintendo Wii U DLC", "Wii U DLC", "Nintendo", "8a gen", "digital", "extension", "blue", (".app", ".tik", ".tmd", ".zip", ".7z"), ("Unofficial - Nintendo - Wii U (Digital) (Deprecated)",), "No-Intro/Unofficial DLC DAT", complexity="experimental"),
    _spec(Platform.GAMECUBE, "Nintendo GameCube", "GameCube", "Nintendo", "6a gen", "disco", "radio_button_checked", "purple", (".iso", ".gcm", ".rvz", ".nkit.iso", ".zip", ".7z"), ("Non-Redump - Nintendo - Nintendo GameCube",), "Redump/Non-Redump DAT", dat_family="redump", complexity="especial"),
    _spec(Platform.WII, "Nintendo Wii", "Wii", "Nintendo", "7a gen", "disco", "radio_button_checked", "blue", (".iso", ".wbfs", ".rvz", ".nkit.iso", ".zip", ".7z"), ("Non-Redump - Nintendo - Wii",), "Redump/Non-Redump DAT", dat_family="redump", complexity="especial"),
    _spec(Platform.WIIU, "Nintendo Wii U", "Wii U", "Nintendo", "8a gen", "disco", "radio_button_checked", "blue", (".wud", ".wux", ".iso", ".zip", ".7z"), ("Non-Redump - Nintendo - Wii U",), "Redump/Non-Redump DAT", dat_family="redump", complexity="experimental"),

    _spec(Platform.SEGACD, "Sega Mega CD / Sega CD", "Mega CD", "Sega", "4a gen", "disco", "album", "blue-grey", CD_EXTENSIONS, ("Non-Redump - Sega - Sega Mega CD + Sega CD",), "Redump/Non-Redump DAT", dat_family="redump", hash_mode="segacd", complexity="especial"),
    _spec(Platform.SATURN, "Sega Saturn", "Saturn", "Sega", "5a gen", "disco", "album", "blue-grey", CD_EXTENSIONS, ("Non-Redump - Sega - Sega Saturn",), "Redump/Non-Redump DAT", dat_family="redump", hash_mode="segacd", complexity="especial"),
    _spec(Platform.DREAMCAST, "Sega Dreamcast", "Dreamcast", "Sega", "6a gen", "disco", "album", "blue-grey", (".gdi", ".cdi", ".chd", ".cue", ".bin", ".zip", ".7z"), ("Non-Redump - Sega - Dreamcast",), "Redump/Non-Redump DAT", dat_family="redump", hash_mode="dreamcast", complexity="especial"),
    _spec(Platform.JAGUAR_CD, "Atari Jaguar CD", "Jaguar CD", "Atari", "5a gen", "disco", "album", "red", CD_EXTENSIONS, ("Non-Redump - Atari - Atari Jaguar CD",), "Redump/Non-Redump DAT", dat_family="redump", complexity="especial"),
    _spec(Platform.PCE_CD, "PC Engine CD / TurboGrafx-CD", "PCE CD", "NEC", "4a gen", "disco", "album", "orange", CD_EXTENSIONS, ("Non-Redump - NEC - PC Engine CD + TurboGrafx CD",), "Redump/Non-Redump DAT", dat_family="redump", complexity="especial", ra_console_id=8),
    _spec(Platform.THREE_DO, "3DO Interactive Multiplayer", "3DO", "Panasonic", "5a gen", "disco", "album", "grey", CD_EXTENSIONS, ("Non-Redump - Panasonic - 3DO Interactive Multiplayer",), "Redump/Non-Redump DAT", dat_family="redump", complexity="especial"),
    _spec(Platform.CDI, "Philips CD-i", "CD-i", "Philips", "4a gen", "disco", "album", "blue", CD_EXTENSIONS, ("Non-Redump - Philips - CD-i",), "Redump/Non-Redump DAT", dat_family="redump", complexity="especial"),
    _spec(Platform.GAME_WAVE, "ZAPiT Game Wave", "Game Wave", "Otros", "6a gen", "disco", "album", "blue-grey", CD_EXTENSIONS, ("Non-Redump - ZAPiT Games - Game Wave Family Entertainment System",), "Redump/Non-Redump DAT", dat_family="redump", complexity="experimental"),

    _spec(Platform.PS1, "Sony PlayStation", "PlayStation", "Sony", "5a gen", "disco", "album", "indigo", CD_EXTENSIONS, ("Non-Redump - Sony - PlayStation",), "Redump/Non-Redump DAT", dat_family="redump", hash_mode="psx", complexity="especial", ra_console_id=12),
    _spec(Platform.PS2, "Sony PlayStation 2", "PlayStation 2", "Sony", "6a gen", "disco", "album", "indigo", (".iso", ".chd", ".cue", ".bin", ".zip", ".7z"), ("Non-Redump - Sony - PlayStation 2",), "Redump/Non-Redump DAT", dat_family="redump", complexity="especial"),
    _spec(Platform.PS3, "Sony PlayStation 3", "PlayStation 3", "Sony", "7a gen", "disco", "album", "indigo", (".iso", ".ird", ".pkg", ".zip", ".7z"), ("Non-Redump - Sony - PlayStation 3",), "Redump/Non-Redump DAT", dat_family="redump", complexity="experimental"),
    _spec(Platform.PSP, "Sony PlayStation Portable", "PSP", "Sony", "7a gen", "portatil", "album", "indigo", (".iso", ".cso", ".chd", ".pbp", ".zip", ".7z"), ("Non-Redump - Sony - PlayStation Portable",), "Redump/No-Intro PSP DAT", dat_family="redump", hash_mode="psp", complexity="especial", ra_console_id=41),
    _spec(Platform.PSP_PSN, "Sony PSP PSN Encrypted", "PSP PSN", "Sony", "7a gen", "digital", "cloud_download", "indigo", (".pkg", ".rif", ".zip", ".7z"), ("Sony - PlayStation Portable (PSN) (Encrypted)",), "No-Intro PSN DAT", complexity="experimental"),
    _spec(Platform.PSP_PSN_DECRYPTED, "Sony PSP PSN Decrypted", "PSP PSN Decrypted", "Sony", "7a gen", "digital", "lock_open", "indigo", (".pkg", ".pbp", ".zip", ".7z"), ("Unofficial - Sony - PlayStation Portable (PSN) (Decrypted)",), "No-Intro decrypted PSN DAT", complexity="experimental"),
    _spec(Platform.PSX2PSP, "PSX2PSP", "PSX2PSP", "Sony", "7a gen", "digital", "swap_horiz", "indigo", (".pbp", ".zip", ".7z"), ("Unofficial - Sony - PlayStation Portable (PSX2PSP)",), "No-Intro PSX2PSP DAT", complexity="experimental"),
    _spec(Platform.VITA, "Sony PlayStation Vita", "PS Vita", "Sony", "8a gen", "portatil", "stay_current_landscape", "indigo", (".vpk", ".pkg", ".zip", ".7z"), ("Unofficial - Sony - PlayStation Vita",), "No-Intro/Unofficial DAT", complexity="experimental"),
    _spec(Platform.VITA_PSN, "Sony PlayStation Vita PSN", "Vita PSN", "Sony", "8a gen", "digital", "cloud_download", "indigo", (".pkg", ".zip", ".7z"), ("Sony - PlayStation Vita (PSN) (Content)",), "No-Intro PSN DAT", complexity="experimental"),
    _spec(Platform.PS3_PSN, "Sony PlayStation 3 PSN", "PS3 PSN", "Sony", "7a gen", "digital", "cloud_download", "indigo", (".pkg", ".rap", ".zip", ".7z"), ("Sony - PlayStation 3 (PSN) (Content)",), "No-Intro PSN DAT", complexity="experimental"),
    _spec(Platform.PS3_PSN_DECRYPTED, "Sony PlayStation 3 PSN Decrypted", "PS3 PSN Dec", "Sony", "7a gen", "digital", "lock_open", "indigo", (".pkg", ".zip", ".7z"), ("Unofficial - Sony - PlayStation 3 (PSN) (Decrypted)",), "No-Intro decrypted PSN DAT", complexity="experimental"),
    _spec(Platform.PSN_PS1, "Sony PS one Classics PSN", "PS1 Classics", "Sony", "7a gen", "digital", "cloud_download", "indigo", (".pkg", ".pbp", ".zip", ".7z"), ("Sony - PlayStation (PS one Classics) (PSN)",), "No-Intro PSN DAT", complexity="experimental"),
    _spec(Platform.PS4_PSN, "Sony PlayStation 4 PSN", "PS4 PSN", "Sony", "8a gen", "digital", "cloud_download", "indigo", (".pkg", ".zip", ".7z"), ("Sony - PlayStation 4 (PSN) (Content)",), "No-Intro PSN DAT", complexity="experimental", notes="Puede incluir DATs logged-in-only."),
    _spec(Platform.PS5_PSN, "Sony PlayStation 5 PSN", "PS5 PSN", "Sony", "9a gen", "digital", "cloud_download", "indigo", (".pkg", ".zip", ".7z"), ("Sony - PlayStation 5 (PSN)",), "No-Intro PSN DAT", complexity="experimental", notes="Puede incluir DATs logged-in-only."),

    _spec(Platform.XBOX, "Microsoft Xbox", "Xbox", "Microsoft", "6a gen", "disco", "album", "green", (".iso", ".xiso", ".zip", ".7z"), ("Non-Redump - Microsoft - Xbox",), "Redump/Non-Redump DAT", dat_family="redump", complexity="experimental"),
    _spec(Platform.XBOX360, "Microsoft Xbox 360", "Xbox 360", "Microsoft", "7a gen", "disco", "album", "green", (".iso", ".god", ".zip", ".7z"), ("Non-Redump - Microsoft - Xbox 360",), "Redump/Non-Redump DAT", dat_family="redump", complexity="experimental"),
    _spec(Platform.XBOXONE, "Microsoft Xbox One", "Xbox One", "Microsoft", "8a gen", "disco", "album", "green", (".iso", ".zip", ".7z"), ("Non-Redump - Microsoft - Xbox One",), "Redump/Non-Redump DAT", dat_family="redump", complexity="experimental"),
    _spec(Platform.XBOX360_TU, "Xbox 360 Title Updates", "X360 TU", "Microsoft", "7a gen", "digital", "system_update_alt", "green", (".tu", ".bin", ".zip", ".7z"), ("Unofficial - Microsoft - Xbox 360 (Title Updates)",), "No-Intro/Unofficial TU DAT", complexity="experimental"),

    _spec(Platform.ACORN_ARCHIMEDES, "Acorn Archimedes", "Archimedes", "Otros", "4a gen", "ordenador", "computer", "blue-grey", DISK_EXTENSIONS, ("Acorn - Archimedes",), "No-Intro floppy DAT"),
    _spec(Platform.ACORN_ATOM, "Acorn Atom", "Acorn Atom", "Otros", "2a gen", "ordenador", "keyboard", "blue-grey", (".tap", ".uef", ".wav", ".zip"), ("Acorn - Atom",), "No-Intro tape DAT"),
    _spec(Platform.BBC_MICRO, "Acorn BBC Micro", "BBC Micro", "Otros", "3a gen", "ordenador", "keyboard", "blue-grey", DISK_EXTENSIONS + (".uef", ".ssd"), ("Acorn - BBC Micro",), "No-Intro DAT", complexity="experimental"),
    _spec(Platform.ACORN_RISC_PC, "Acorn Risc PC", "Risc PC", "Otros", "5a gen", "ordenador", "computer", "blue-grey", DISK_EXTENSIONS, ("Acorn - Risc PC",), "No-Intro floppy DAT"),
    _spec(Platform.APRICOT_PC, "ACT Apricot PC Xi", "Apricot PC", "Otros", "3a gen", "ordenador", "computer", "blue-grey", DISK_EXTENSIONS, ("ACT - Apricot PC Xi",), "No-Intro floppy DAT"),
    _spec(Platform.APF_MP1000, "APF MP-1000", "APF MP-1000", "Otros", "2a gen", "sobremesa", "videogame_asset", "brown", (".bin", ".zip"), ("APF - MP-1000",), "No-Intro cart DAT"),
    _spec(Platform.APF_IMAGINATION, "APF Imagination Machine", "APF Imagination", "Otros", "2a gen", "ordenador", "keyboard", "brown", (".tap", ".wav", ".zip"), ("APF - Imagination Machine",), "No-Intro tape DAT"),
    _spec(Platform.APPLE_I, "Apple I", "Apple I", "Apple", "1a gen", "ordenador", "keyboard", "grey", (".bin", ".tap", ".zip"), ("Apple - I",), "No-Intro tape DAT"),
    _spec(Platform.APPLE_II_PLUS, "Apple II Plus", "Apple II Plus", "Apple", "2a gen", "ordenador", "keyboard", "grey", DISK_EXTENSIONS, ("Apple - II Plus",), "No-Intro floppy DAT"),
    _spec(Platform.APPLE_IIE, "Apple IIe", "Apple IIe", "Apple", "2a gen", "ordenador", "keyboard", "grey", DISK_EXTENSIONS, ("Apple - IIe",), "No-Intro floppy DAT"),
    _spec(Platform.APPLE_IIGS, "Apple IIGS", "Apple IIGS", "Apple", "3a gen", "ordenador", "keyboard", "grey", DISK_EXTENSIONS, ("Apple - IIGS",), "No-Intro floppy DAT"),
    _spec(Platform.MACINTOSH, "Apple Macintosh", "Macintosh", "Apple", "3a gen", "ordenador", "desktop_mac", "grey", DISK_EXTENSIONS, ("Apple - Macintosh",), "No-Intro floppy DAT"),
    _spec(Platform.COMMODORE_PLUS4, "Commodore Plus/4", "Plus/4", "Commodore", "3a gen", "ordenador", "keyboard", "brown", (".prg", ".crt", ".d64", ".tap", ".zip"), ("Commodore - Plus-4",), "No-Intro DAT"),
    _spec(Platform.VIC20, "Commodore VIC-20", "VIC-20", "Commodore", "2a gen", "ordenador", "keyboard", "brown", (".prg", ".crt", ".d64", ".tap", ".zip"), ("Commodore - VIC-20",), "No-Intro DAT"),
    _spec(Platform.C64_PP, "Commodore 64 PP", "C64 PP", "Commodore", "3a gen", "ordenador", "keyboard", "brown", (".prg", ".zip"), ("Commodore - Commodore 64 (PP)",), "No-Intro DAT"),
    _spec(Platform.C64_TAPES, "Commodore 64 Tapes", "C64 Tapes", "Commodore", "3a gen", "ordenador", "keyboard", "brown", (".tap", ".t64", ".wav", ".zip"), ("Commodore - Commodore 64 (Tapes)",), "No-Intro tape DAT"),
    _spec(Platform.ZX_SPECTRUM_PLUS3, "Sinclair ZX Spectrum +3", "ZX Spectrum +3", "Otros", "3a gen", "ordenador", "keyboard", "green", (".dsk", ".tap", ".tzx", ".zip"), ("Sinclair - ZX Spectrum +3",), "No-Intro DAT"),
    _spec(Platform.SHARP_X1, "Sharp X1", "Sharp X1", "Otros", "3a gen", "ordenador", "keyboard", "blue-grey", DISK_EXTENSIONS, ("Sharp - X1",), "No-Intro DAT"),
    _spec(Platform.TELE_NOVA_COMPIS, "TeleNova Compis", "Compis", "Otros", "3a gen", "ordenador", "computer", "blue-grey", DISK_EXTENSIONS, ("TeleNova - Compis",), "No-Intro DAT"),
    _spec(Platform.TOSHIBA_PASOPIA, "Toshiba Pasopia", "Pasopia", "Otros", "3a gen", "ordenador", "keyboard", "blue-grey", DISK_EXTENSIONS, ("Toshiba - Pasopia",), "No-Intro DAT"),
    _spec(Platform.TOSHIBA_VISICOM, "Toshiba Visicom", "Visicom", "Otros", "2a gen", "sobremesa", "videogame_asset", "blue-grey", (".bin", ".zip"), ("Toshiba - Visicom",), "No-Intro DAT"),
    _spec(Platform.YAMAHA_COPERA, "Yamaha Copera", "Copera", "Otros", "5a gen", "sobremesa", "videogame_asset", "blue-grey", (".bin", ".zip"), ("Yamaha - Copera",), "No-Intro DAT"),

    _spec(Platform.BALLY_ASTROCADE, "Bally Astrocade", "Astrocade", "Otros", "2a gen", "sobremesa", "videogame_asset", "deep-orange", (".bin", ".rom", ".zip"), ("Bally - Astrocade",), "No-Intro cart DAT"),
    _spec(Platform.BALLY_ASTROCADE_TAPES, "Bally Astrocade Tapes", "Astrocade Tapes", "Otros", "2a gen", "ordenador", "keyboard", "deep-orange", (".tap", ".wav", ".zip"), ("Bally - Astrocade (Tapes)",), "No-Intro tape DAT"),
    _spec(Platform.RCA_STUDIO_II, "RCA Studio II", "Studio II", "Otros", "2a gen", "sobremesa", "videogame_asset", "grey", (".bin", ".zip"), ("RCA - Studio II",), "No-Intro DAT"),
    _spec(Platform.ENTEX_ADVENTURE, "Entex Adventure Vision", "Adventure Vision", "Otros", "2a gen", "sobremesa", "videogame_asset", "grey", (".bin", ".zip"), ("Entex - Adventure Vision",), "No-Intro DAT"),
    _spec(Platform.EPOCH_GAME_POCKET, "Epoch Game Pocket Computer", "Game Pocket", "Otros", "portatil clasica", "portatil", "stay_current_landscape", "grey", (".bin", ".zip"), ("Epoch - Game Pocket Computer",), "No-Intro DAT"),
    _spec(Platform.NICHIBUTSU_MY_VISION, "Nichibutsu My Vision", "My Vision", "Otros", "2a gen", "sobremesa", "videogame_asset", "grey", (".bin", ".zip"), ("Nichibutsu - My Vision",), "No-Intro DAT"),
    _spec(Platform.SETA_ALECK64, "Seta Aleck64", "Aleck64", "Otros", "5a gen", "arcade", "casino", "green", ARCADE_EXTENSIONS + (".z64", ".n64"), ("Seta - Aleck64",), "No-Intro/MAME DAT", dat_family="arcade", complexity="especial"),
    _spec(Platform.BANDAI_DESIGN_MASTER, "Bandai Design Master Denshi Mangajuku", "Design Master", "Bandai", "5a gen", "sobremesa", "draw", "pink", (".bin", ".zip"), ("Bandai - Design Master Denshi Mangajuku",), "No-Intro DAT"),
    _spec(Platform.BANDAI_RX78, "Bandai Gundam RX-78", "Gundam RX-78", "Bandai", "3a gen", "ordenador", "keyboard", "pink", (".bin", ".zip"), ("Bandai - Gundam RX-78",), "No-Intro DAT"),
    _spec(Platform.BENESSE_POCKET_CHALLENGE_V2, "Benesse Pocket Challenge V2", "Pocket Challenge V2", "Otros", "portatil clasica", "portatil", "school", "green", (".bin", ".zip"), ("Benesse - Pocket Challenge V2",), "No-Intro DAT"),
    _spec(Platform.BENESSE_POCKET_CHALLENGE_W, "Benesse Pocket Challenge W", "Pocket Challenge W", "Otros", "portatil clasica", "portatil", "school", "green", (".bin", ".zip"), ("Benesse - Pocket Challenge W",), "No-Intro DAT"),
    _spec(Platform.VTECH_MOBIGO, "VTech MobiGo", "MobiGo", "Otros", "7a gen", "portatil", "school", "green", (".bin", ".zip"), ("VTech - Mobigo",), "No-Intro DAT"),
    _spec(Platform.NOKIA_NGAGE_2, "Nokia N-Gage 2.0", "N-Gage 2.0", "Otros", "7a gen", "portatil", "phone_iphone", "blue-grey", (".sis", ".ngage", ".zip"), ("Nokia - N-Gage 2.0",), "No-Intro WIP DAT", complexity="experimental"),
    _spec(Platform.OUYA, "Ouya", "Ouya", "Otros", "8a gen", "digital", "sports_esports", "grey", (".apk", ".zip", ".7z"), ("Ouya - Ouya",), "No-Intro DAT", complexity="experimental"),
    _spec(Platform.PCFX, "NEC PC-FX", "PC-FX", "NEC", "5a gen", "disco", "album", "orange", CD_EXTENSIONS, ("NEC - PC-FX", "PC-FX"), "Redump/No-Intro DAT", dat_family="redump", complexity="especial", ra_console_id=49),
    _spec(Platform.NEOGEO_CD, "Neo Geo CD", "Neo Geo CD", "SNK", "4a gen", "disco", "album", "amber", CD_EXTENSIONS, ("SNK - Neo Geo CD", "Neo Geo CD"), "Redump/Non-Redump DAT", dat_family="redump", complexity="especial", ra_console_id=56),
    _spec(Platform.WASM4, "WASM-4", "WASM-4", "Otros", "experimental", "experimental", "terminal", "purple", (".wasm", ".zip"), ("WASM-4",), "RA/No-Intro community DAT", complexity="experimental", ra_console_id=72),
    _spec(Platform.UZEBOX, "Uzebox", "Uzebox", "Otros", "7a gen", "sobremesa", "memory", "green", (".uze", ".hex", ".bin", ".zip"), ("Uzebox",), "No-Intro/RA DAT", complexity="experimental", ra_console_id=80),
    _spec(Platform.INTERTON_VC4000, "Interton VC 4000", "VC 4000", "Otros", "2a gen", "sobremesa", "videogame_asset", "grey", (".bin", ".rom", ".zip"), ("Interton - VC 4000", "Interton VC 4000"), "No-Intro DAT", ra_console_id=74),
    _spec(Platform.ELEKTOR_TVGC, "Elektor TV Games Computer", "Elektor TVGC", "Otros", "2a gen", "sobremesa", "videogame_asset", "grey", (".bin", ".rom", ".zip"), ("Elektor - TV Games Computer",), "No-Intro DAT", ra_console_id=75),

    _spec(Platform.MAME, "MAME Arcade", "MAME", "Arcade", "arcade", "arcade", "sports_esports", "red", ARCADE_EXTENSIONS, ("MAME", "MAME - ROMs", "MAME XML"), "MAME official XML/DAT", dat_family="mame", romset_recommended="MAME romset de la misma version que el DAT. Split/merged/non-merged debe mantenerse coherente.", collection_tip="Arcade no usa 1G1R de consola: parents, clones, BIOS, devices y CHD pueden ser dependencias reales.", complexity="arcade", notes="Los ZIP se tratan como sets completos por nombre, no como ROMs internas sueltas."),
    _spec(Platform.MAME_CHD, "MAME CHD", "MAME CHD", "Arcade", "arcade", "arcade", "storage", "red", (".chd", ".zip", ".7z"), ("MAME CHD", "MAME - CHDs"), "MAME CHD DAT/XML", dat_family="mame", romset_recommended="CHDs de la misma version y jerarquia de carpetas que el set MAME.", collection_tip="Los CHD suelen depender del set ZIP padre; RetroPerfect los marca como dependencias, no como duplicados normales.", complexity="arcade"),
    _spec(Platform.MAME_SOFTWARE_LIST, "MAME Software Lists", "MAME SL", "Arcade", "varios", "arcade", "list_alt", "red", (".zip", ".7z", ".chd", ".bin", ".rom"), ("MAME Software List", "MAME SL"), "MAME Software List DAT", dat_family="mame", romset_recommended="Software Lists de la misma version de MAME.", collection_tip="Es frontera entre arcade y ordenadores/consolas; conviene validar por lista concreta.", complexity="arcade"),
    _spec(Platform.MAME2003PLUS, "MAME 2003-Plus", "MAME 2003+", "Arcade", "arcade", "arcade", "sports_esports", "deep-orange", ARCADE_EXTENSIONS, ("MAME 2003-Plus", "MAME 2003 Plus"), "DAT generado por core MAME 2003-Plus", dat_family="mame", romset_recommended="Romset exacto para la version/core MAME 2003-Plus.", collection_tip="Especialmente sensible a version de romset; no mezclar con MAME actual.", complexity="arcade"),
    _spec(Platform.FBNEO, "FinalBurn Neo Arcade", "FBNeo", "Arcade", "arcade", "arcade", "sports_esports", "orange", ARCADE_EXTENSIONS, ("FinalBurn Neo", "FBNeo", "FB Alpha - Arcade Games"), "FBNeo DAT oficial/libretro", dat_family="fbneo", romset_recommended="Romset FBNeo exacto para el core/version usada.", collection_tip="FBNeo tambien depende de parents/clones y BIOS; no aplicar limpieza de consola a ciegas.", complexity="arcade", ra_console_id=27),
    _spec(Platform.FBA, "FinalBurn Alpha", "FBA", "Arcade", "arcade", "arcade", "sports_esports", "orange", ARCADE_EXTENSIONS, ("FinalBurn Alpha", "FB Alpha"), "FBA DAT especifico de version", dat_family="fbneo", romset_recommended="Romset FBA exacto; no mezclar con FBNeo si no se reconstruye.", complexity="arcade"),
    _spec(Platform.HBMAME, "HBMAME", "HBMAME", "Arcade", "arcade", "arcade", "science", "purple", ARCADE_EXTENSIONS, ("HBMAME",), "HBMAME XML/DAT", dat_family="mame", romset_recommended="Romset HBMAME de la misma version; orientado a homebrew/hacks arcade.", collection_tip="Aqui clones, hacks y bootlegs pueden ser precisamente el objetivo; reglas de exclusion deben revisarse.", complexity="arcade"),
    _spec(Platform.NEOGEO_MVS, "Neo Geo MVS Arcade", "Neo Geo MVS", "Arcade", "arcade", "arcade", "casino", "amber", ARCADE_EXTENSIONS, ("SNK - Neo Geo MVS", "FBNeo - Neo Geo", "MAME - Neo Geo"), "MAME/FBNeo Neo Geo DAT", dat_family="arcade", romset_recommended="Mantener BIOS neogeo.zip y version de DAT/core coherentes.", collection_tip="Neo Geo requiere BIOS y puede compartir sets con MAME/FBNeo.", complexity="arcade", ra_console_id=24),
    _spec(Platform.CPS1, "Capcom CPS-1", "CPS-1", "Arcade", "arcade", "arcade", "casino", "red", ARCADE_EXTENSIONS, ("Capcom CPS-1", "CPS1"), "MAME/FBNeo arcade DAT", dat_family="arcade", complexity="arcade"),
    _spec(Platform.CPS2, "Capcom CPS-2", "CPS-2", "Arcade", "arcade", "arcade", "casino", "red", ARCADE_EXTENSIONS, ("Capcom CPS-2", "CPS2"), "MAME/FBNeo arcade DAT", dat_family="arcade", complexity="arcade"),
    _spec(Platform.CPS3, "Capcom CPS-3", "CPS-3", "Arcade", "arcade", "arcade", "casino", "red", ARCADE_EXTENSIONS, ("Capcom CPS-3", "CPS3"), "MAME/FBNeo arcade DAT", dat_family="arcade", complexity="arcade"),
    _spec(Platform.SEGA_MODEL2, "Sega Model 2", "Model 2", "Arcade", "arcade", "arcade", "precision_manufacturing", "blue-grey", ARCADE_EXTENSIONS, ("Sega Model 2", "MAME - Sega Model 2"), "MAME/Model 2 DAT", dat_family="arcade", complexity="arcade"),
    _spec(Platform.SEGA_MODEL3, "Sega Model 3", "Model 3", "Arcade", "arcade", "arcade", "precision_manufacturing", "blue-grey", ARCADE_EXTENSIONS, ("Sega Model 3", "MAME - Sega Model 3"), "MAME/Model 3 DAT", dat_family="arcade", complexity="arcade"),
    _spec(Platform.NAOMI, "Sega NAOMI", "NAOMI", "Arcade", "arcade", "arcade", "memory", "blue-grey", (".zip", ".7z", ".chd", ".bin", ".lst"), ("Sega NAOMI", "MAME - Sega NAOMI"), "MAME/Redump arcade DAT", dat_family="arcade", complexity="arcade"),
    _spec(Platform.ATOMISWAVE, "Sammy Atomiswave", "Atomiswave", "Arcade", "arcade", "arcade", "memory", "deep-orange", ARCADE_EXTENSIONS, ("Sammy Atomiswave", "MAME - Atomiswave"), "MAME/FBNeo arcade DAT", dat_family="arcade", complexity="arcade"),
    _spec(Platform.CAVE_ARCADE, "Cave Arcade", "Cave", "Arcade", "arcade", "arcade", "casino", "purple", ARCADE_EXTENSIONS, ("Cave", "MAME - Cave"), "MAME/FBNeo arcade DAT", dat_family="arcade", complexity="arcade"),
    _spec(Platform.TAITO_F3, "Taito F3", "Taito F3", "Arcade", "arcade", "arcade", "casino", "blue", ARCADE_EXTENSIONS, ("Taito F3", "MAME - Taito F3"), "MAME/FBNeo arcade DAT", dat_family="arcade", complexity="arcade"),
    _spec(Platform.IGS_PGM, "IGS PolyGame Master", "IGS PGM", "Arcade", "arcade", "arcade", "casino", "green", ARCADE_EXTENSIONS, ("IGS PolyGame Master", "PGM"), "MAME/FBNeo arcade DAT", dat_family="arcade", complexity="arcade"),
)


for _extra_spec in _EXTRA_SPECS:
    PLATFORM_SPECS[_extra_spec.id] = _extra_spec


_EXTRA_PRIORITY_PLATFORMS: tuple[Platform, ...] = tuple(spec.id for spec in _EXTRA_SPECS)
PRIORITY_PLATFORMS = PRIORITY_PLATFORMS + _EXTRA_PRIORITY_PLATFORMS


RA_CONSOLE_IDS: dict[Platform, tuple[int, bool]] = {
    Platform.MD: (1, True),
    Platform.N64: (2, True),
    Platform.SNES: (3, True),
    Platform.GB: (4, True),
    Platform.GBA: (5, True),
    Platform.GBC: (6, True),
    Platform.NES: (7, True),
    Platform.PCE: (8, True),
    Platform.SGX: (8, True),
    Platform.SEGACD: (9, True),
    Platform.S32X: (10, True),
    Platform.SMS: (11, True),
    Platform.PS1: (12, True),
    Platform.LYNX: (13, True),
    Platform.NGP: (14, True),
    Platform.NGPC: (14, True),
    Platform.GG: (15, True),
    Platform.GAMECUBE: (16, True),
    Platform.JAGUAR: (17, True),
    Platform.NDS: (18, True),
    Platform.WII: (19, True),
    Platform.WIIU: (20, False),
    Platform.WIIU_CDN: (20, False),
    Platform.WIIU_DLC: (20, False),
    Platform.PS2: (21, True),
    Platform.XBOX: (22, False),
    Platform.ODYSSEY2: (23, True),
    Platform.POKEMON_MINI: (24, True),
    Platform.A2600: (25, True),
    Platform.MAME: (27, True),
    Platform.MAME_CHD: (27, True),
    Platform.MAME_SOFTWARE_LIST: (27, True),
    Platform.MAME2003PLUS: (27, True),
    Platform.FBNEO: (27, True),
    Platform.FBA: (27, True),
    Platform.HBMAME: (27, True),
    Platform.NEOGEO_MVS: (27, True),
    Platform.CPS1: (27, True),
    Platform.CPS2: (27, True),
    Platform.CPS3: (27, True),
    Platform.SEGA_MODEL2: (27, True),
    Platform.SEGA_MODEL3: (27, True),
    Platform.NAOMI: (27, True),
    Platform.ATOMISWAVE: (27, True),
    Platform.CAVE_ARCADE: (27, True),
    Platform.TAITO_F3: (27, True),
    Platform.IGS_PGM: (27, True),
    Platform.SETA_ALECK64: (27, True),
    Platform.VB: (28, True),
    Platform.MSX: (29, True),
    Platform.MSX2: (29, True),
    Platform.C64: (30, False),
    Platform.C64_PP: (30, False),
    Platform.C64_TAPES: (30, False),
    Platform.VIC20: (34, False),
    Platform.AMIGA: (35, False),
    Platform.ATARI_ST: (36, False),
    Platform.CPC: (37, True),
    Platform.APPLE_II: (38, True),
    Platform.APPLE_II_PLUS: (38, True),
    Platform.APPLE_IIE: (38, True),
    Platform.APPLE_IIGS: (38, True),
    Platform.SATURN: (39, True),
    Platform.DREAMCAST: (40, True),
    Platform.PSP: (41, True),
    Platform.CDI: (42, False),
    Platform.THREE_DO: (43, True),
    Platform.COLECO: (44, True),
    Platform.INTV: (45, True),
    Platform.VECTREX: (46, True),
    Platform.PC88: (47, True),
    Platform.PC98: (48, False),
    Platform.PCFX: (49, True),
    Platform.A5200: (50, False),
    Platform.A7800: (51, True),
    Platform.X68000: (52, False),
    Platform.WS: (53, True),
    Platform.WSC: (53, True),
    Platform.SUPERCASSETTE: (55, False),
    Platform.NEOGEO_CD: (56, True),
    Platform.CHANNELF: (57, True),
    Platform.ZX_SPECTRUM: (59, False),
    Platform.ZX_SPECTRUM_PLUS3: (59, False),
    Platform.GAME_WATCH: (60, False),
    Platform.NGAGE: (61, False),
    Platform.NOKIA_NGAGE_2: (61, False),
    Platform.N3DS: (62, False),
    Platform.N3DS_DIGITAL: (62, False),
    Platform.N3DS_DLC: (62, False),
    Platform.N3DS_CIA: (62, False),
    Platform.SUPERVISION: (63, True),
    Platform.SHARP_X1: (64, False),
    Platform.PICO: (68, False),
    Platform.MEGA_DUCK: (69, True),
    Platform.ZEEBO: (70, False),
    Platform.ARDUBOY: (71, True),
    Platform.WASM4: (72, True),
    Platform.ARCADIA: (73, True),
    Platform.INTERTON_VC4000: (74, True),
    Platform.ELEKTOR_TVGC: (75, True),
    Platform.PCE_CD: (76, True),
    Platform.JAGUAR_CD: (77, True),
    Platform.DSI: (78, True),
    Platform.DSIWARE: (78, True),
    Platform.DSI_CDN: (78, True),
    Platform.UZEBOX: (80, True),
    Platform.FDS: (81, True),
    Platform.PS3: (82, False),
    Platform.PS3_PSN: (82, False),
    Platform.PS3_PSN_DECRYPTED: (82, False),
}


for _platform, (_ra_console_id, _ra_active) in RA_CONSOLE_IDS.items():
    if _platform in PLATFORM_SPECS:
        PLATFORM_SPECS[_platform] = replace(PLATFORM_SPECS[_platform], ra_console_id=_ra_console_id, ra_active=_ra_active)


def platform_spec(platform: Platform | str) -> PlatformSpec:
    parsed = Platform(platform)
    return PLATFORM_SPECS[parsed]


def list_platforms() -> list[PlatformSpec]:
    return [PLATFORM_SPECS[item] for item in PRIORITY_PLATFORMS]


def platform_options() -> dict[str, str]:
    return {spec.id.value: f"{spec.short_name} · {spec.brand}" for spec in list_platforms()}


def platform_from_dat_name(name: str) -> Platform | None:
    lowered = name.lower()
    for spec in list_platforms():
        if any(alias.lower() in lowered for alias in spec.dat_aliases):
            return spec.id
    return None
